services:
  - type: web
    name: mapleluxe
    env: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: build
    skipStart: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x
